# DATABASE
CREATE DATABASE COMERCIO;

# TABELAS
CREATE TABLE CIDADE(
	CODIGO INTEGER NOT NULL,
	NOME VARCHAR(50),
	UF CHARACTER(2)
);

CREATE TABLE CLIENTE(
	CODIGO INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CODCIDADE INTEGER NOT NULL
);

CREATE TABLE PF(
	CPF CHARACTER(11) UNIQUE NOT NULL,
	COD INTEGER NOT NULL
);

CREATE TABLE PJ(
	CNPJ CHARACTER(11) UNIQUE NOT NULL,
	COD INTEGER NOT NULL
);
ALTER TABLE PJ ADD COLUMNS(CNPJ CHARACTER(11) UNIQUE NOT NULL);

CREATE TABLE PRODUTO(
	CODIGO INTEGER NOT NULL,
	NOME VARCHAR(30),
	VALOR REAL
);

CREATE TABLE PEDIDO(
	NF CHARACTER(44) NOT NULL,
	DATA_PEDIDO DATE NOT NULL,
	COD_PF INTEGER
);

CREATE TABLE ITEM_PEDIDO(
	QUANTIDADE INTEGER,
	CODPRODUTO INTEGER NOT NULL,
	NF CHARACTER(44) NOT NULL
);

# CONSTRAINTSS

# CHAVE PRIMARIA

ALTER TABLE CIDADE ADD CONSTRAINTS CIDADE_PKEY PRIMARY KEY(CODIGO);

ALTER TABLE CLIENTE ADD CONSTRAINTS CLIENTE_PKEY PRIMARY KEY(CODIGO);

ALTER TABLE PRODUTO ADD CONSTRAINTS PRODUTO_PKEY PRIMARY KEY(CODIGO);

ALTER TABLE PEDIDO ADD CONSTRAINTS PEDIDO_PKEY PRIMARY KEY(NF);

# CHAVE ESTRAGEIRA

ALTER TABLE CLIENTE ADD CONSTRAINTS CLIENTE_CIDADE_FKEY FOREIGN KEY(CODCIDADE)
	REFERENCES CIDADE(CODIGO);
	
ALTER TABLE PF ADD CONSTRAINTS PF_CLIENTE_FKEY FOREIGN KEY(COD)
	REFERENCES CLIENTE(CODIGO);

ALTER TABLE PJ ADD CONSTRAINTS PJ_CLIENTE_FKEY FOREIGN KEY(COD)
	REFERENCES CLIENTE(CODIGO);

ALTER TABLE PEDIDO ADD CONSTRAINTS PEDIDO_CLIENTE_FKEY FOREIGN KEY(COD_PF)
	REFERENCES CLIENTE(CODIGO);

ALTER TABLE ITEM_PEDIDO ADD CONSTRAINTS ITEM_PEDIDO_PRODUTO_FKEY FOREIGN KEY(CODPRODUTO)
	REFERENCES PRODUTO(CODIGO);

ALTER TABLE ITEM_PEDIDO ADD CONSTRAINTS ITEM_PEDIDO_PEDIDO_FKEY FOREIGN KEY(NF)
	REFERENCES PEDIDO(NF);