SELECT C.NOME, COUNT(*) AS QUANTIDADE
FROM CLIENTE C, PEDIDO P
WHERE C.CODIGO = P.COD_PF
GROUP BY NOME;

SELECT P.NOME
FROM PRODUTO P
LEFT OUTER JOIN ITEM_PEDIDO ON (P.CODIGO = ITEM_PEDIDO.CODPRODUTO)
WHERE ITEM_PEDIDO.CODPRODUTO IS NULL;

SELECT P.NOME
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO ON (P.CODIGO = ITEM_PEDIDO.CODPRODUTO)
GROUP BY NOME
HAVING COUNT(*) > 3;

SELECT C.NOME, P.NF FROM CLIENTE C, PEDIDO P
WHERE (C.NOME, P.NF) IN (SELECT C.NOME, P.NF
			FROM CLIENTE C, CIDADE T, PEDIDO P
			WHERE C.CODCIDADE = T.CODIGO AND C.CODIGO = P.COD_PF
			AND (T.UF = 'RJ' OR T.UF = 'SP'));

SELECT P.VALOR * I.QUANTIDADE AS VALOR_TOTAL
FROM PRODUTO P, ITEM_PEDIDO I
WHERE P.CODIGO = I.CODPRODUTO;

SELECT P.NF, P.DATA_PEDIDO AS "DATA", P.COD_PF
FROM PEDIDO P
INNER JOIN ITEM_PEDIDO ON(P.NF = ITEM_PEDIDO.NF)
WHERE QUANTIDADE > 5;
