SELECT SEXO, COUNT(*) AS QUANTIDADE FROM USUARIO
GROUP BY SEXO;

SELECT NOME, SEXO FROM USUARIO
WHERE SEXO = 'M' AND NOME LIKE 'R%' ;

SELECT NOME, COUNT(*) AS QUANTIDADE FROM USUARIO T
INNER JOIN USUARIO_AMIGO P ON (T.IDUSUARIO = P.IDUSUARIO)
GROUP BY NOME
HAVING COUNT(*) > 2
ORDER BY QTD DESC;

SELECT NOME, COUNT(*) AS QUANTIDADE FROM USUARIO
INNER JOIN USUARIO_SEGUIDOR ON (USUARIO.IDUSUARIO = USUARIO_SEGUIDOR.IDUSUARIO)
GROUP BY NOME
ORDER BY QUANTIDADE DESC;

SELECT P.NOME FROM USUARIO P
LEFT OUTER JOIN USUARIO_GRUPO ON (P.IDUSUARIO = USUARIO_GRUPO.IDUSUARIO)
WHERE USUARIO_GRUPO.IDUSUARIO IS NULL;

SELECT AMIGO.NOME FROM AMIGO
WHERE NOME IN (SELECT C.NOME
			  	FROM AMIGO C, USUARIO_AMIGO T
			  	WHERE C.IDAMIGO = T.IDAMIGO 
			   	AND T.IDUSUARIO = 4);

SELECT T.IDUSUARIO, T.NOME, P.IDPUBLI, P.PUBLI_TIPO
FROM USUARIO T, PUBLICACAO P, USUARIO_PUBLICACAO C
WHERE C.IDUSUARIO = T.IDUSUARIO AND C.IDPUBLI = P.IDPUBLI
ORDER BY T.IDUSUARIO;

SELECT NOME FROM USUARIO
WHERE NOME IN (SELECT C.NOME
			  	FROM USUARIO C, PUBLICACAO P, USUARIO_PUBLICACAO T, CURTIDA M
			  	WHERE C.IDUSUARIO = T.IDUSUARIO 
			   	AND P.IDPUBLI = T.IDPUBLI 
				AND P.IDPUBLI = M.IDPUBLI
			   	GROUP BY C.NOME
			  	HAVING COUNT(*) > 5);

SELECT P.NOME, COUNT(C.CELULAR) AS NUM_CELULARES FROM USUARIO P
INNER JOIN CONTATO C ON (P.IDUSUARIO = C.IDUSUARIO)
GROUP BY NOME
HAVING COUNT(C.CELULAR) > 1;

SELECT P.NOME, C.EMAIL FROM USUARIO P
INNER JOIN CONTATO C ON (P.IDUSUARIO = C.IDUSUARIO)
WHERE C.EMAIL LIKE '%@gmail.com';
