# INSERINDO DATAS DE ANIVERSARIO DOS USUARIOS
INSERT INTO DATA_ANIVERSARIO VALUES(1, '02/05/2003');
INSERT INTO DATA_ANIVERSARIO VALUES(2, '28/07/1975');
INSERT INTO DATA_ANIVERSARIO VALUES(3, '06/01/1964');
INSERT INTO DATA_ANIVERSARIO VALUES(4, '25/04/2004');
INSERT INTO DATA_ANIVERSARIO VALUES(5, '08/01/1983');
INSERT INTO DATA_ANIVERSARIO VALUES(6, '18/09/1972');
INSERT INTO DATA_ANIVERSARIO VALUES(7, '11/09/1967');
INSERT INTO DATA_ANIVERSARIO VALUES(8, '02/10/1976');
INSERT INTO DATA_ANIVERSARIO VALUES(9, '08/10/1972');
INSERT INTO DATA_ANIVERSARIO VALUES(10, '06/08/1967');
INSERT INTO DATA_ANIVERSARIO VALUES(11, '07/08/1997');


# INSERINDO DESCRIÇÕES
INSERT INTO DESCRICAO VALUES(1, 'Estudante de Sistemas de Informação');
INSERT INTO DESCRICAO VALUES(2, 'Estudante de Direito');
INSERT INTO DESCRICAO VALUES(3, 'Estudante de Medicina');
INSERT INTO DESCRICAO VALUES(4, 'Apaixonado por flores');
INSERT INTO DESCRICAO VALUES(5, 'O mundo é dos loucos');
INSERT INTO DESCRICAO VALUES(6, 'Apaixonado por tecnologia');
INSERT INTO DESCRICAO VALUES(7, 'Vasco da Gama');
INSERT INTO DESCRICAO VALUES(8, 'Flamenguita roxo');
INSERT INTO DESCRICAO VALUES(9, 'Amante das estrelas');
INSERT INTO DESCRICAO VALUES(10, 'Fã do Casimiro');
INSERT INTO DESCRICAO VALUES(11, 'Um menino muito maluquinho');
INSERT INTO DESCRICAO VALUES(12, 'O sol é a estrela mais brilhante do universo');
INSERT INTO DESCRICAO VALUES(13, 'Dias de luta, dias de glória');
INSERT INTO DESCRICAO VALUES(14, 'Perfil especializado em educação financeira');
INSERT INTO DESCRICAO VALUES(15, 'RECEBA!!');

# INSERINDO USUARIOS
INSERT INTO USUARIO VALUES(1, 'Hermine Pemberton', 'F', NULL, 1);
INSERT INTO USUARIO VALUES(2, 'Dana Cousins', 'F', 4, 1);
INSERT INTO USUARIO VALUES(3, 'Rheba Bouvet', 'F', 2, 5);
INSERT INTO USUARIO VALUES(4, 'Maxwell Melia', 'M', 1, 2);
INSERT INTO USUARIO VALUES(5, 'Rosario Hodge', 'M', 8, 8);
INSERT INTO USUARIO VALUES(6, 'Frankie Lawson', 'M', 4, 1);
INSERT INTO USUARIO VALUES(7, 'Raeann Barber', 'M', 11, 5);
INSERT INTO USUARIO VALUES(8, 'Karisa Savage', 'F', 8, 10);
INSERT INTO USUARIO VALUES(9, 'Beverley Schofield', 'F', 6, 8);
INSERT INTO USUARIO VALUES(10, 'Eura Grant', 'F', NULL, 4);
INSERT INTO USUARIO VALUES(11, 'Luke Mcgrath', 'M', NULL, 11);
INSERT INTO USUARIO VALUES(12, 'Eugene Storey', 'M', 1, 7);
INSERT INTO USUARIO VALUES(13, 'Kristen Bate', 'M', NULL, 9);
INSERT INTO USUARIO VALUES(14, 'Leeanne Morgan', 'F', 3, 11);
INSERT INTO USUARIO VALUES(15, 'Doreen Collins', 'F', 5, 3);
INSERT INTO USUARIO VALUES(16, 'Juliann George', 'M', 13, 6);
INSERT INTO USUARIO VALUES(17, 'Renea Boyd', 'F', 6, 7);
INSERT INTO USUARIO VALUES(18, 'Craig Bray', 'M', 12, 9);
INSERT INTO USUARIO VALUES(19, 'Sonny Garner', 'M', 8, 10);
INSERT INTO USUARIO VALUES(20, 'Margy Douglas', 'F', 7, 4);


#INSERINDO GRUPO
INSERT INTO GRUPO VALUES(1, 'Astronomia', 9);
INSERT INTO GRUPO VALUES(2, 'Fã clube Casimiro', 10);
INSERT INTO GRUPO VALUES(3, 'Do Mil ao MILHÃO', 14);
INSERT INTO GRUPO VALUES(4, 'Luva de pedreiro', 15);
INSERT INTO GRUPO VALUES(5, 'Programadores', 1);
INSERT INTO GRUPO VALUES(6, 'Amantes de flores', 4);

# INSERINDO CONTATO
INSERT INTO CONTATO VALUES(1, 'herm@yahoo.com', '93989562778', 1);
INSERT INTO CONTATO VALUES(2, 'dana@gmail.com', '22973926330', 2);
INSERT INTO CONTATO VALUES(3, 'rheba@outlook.com', '42992139222', 3);
INSERT INTO CONTATO VALUES(4, 'max@hotmail.com', '96986018731', 4);
INSERT INTO CONTATO VALUES(5, 'ros@yahoo.com', '96985121421', 5);
INSERT INTO CONTATO VALUES(6, 'frank@yahoo.com', '62986346320', 6);
INSERT INTO CONTATO VALUES(7, 'barber14@gmail.com', '55979616630', 7);
INSERT INTO CONTATO VALUES(8, 'savage777@gmail.com', '84991675686', 8);
INSERT INTO CONTATO VALUES(9, 'bevscho@gmail.com', '79982704082', 9);
INSERT INTO CONTATO VALUES(10, 'eugra@hotmail.com', '68986311333', 10);
INSERT INTO CONTATO VALUES(11, 'mcluke55@outlook.com', '95969656085', 11);
INSERT INTO CONTATO VALUES(12, 'eustrorey@bing.com', '67988622177', 12);
INSERT INTO CONTATO VALUES(13, 'kris147@gmail.com', '79968358634', 13);
INSERT INTO CONTATO VALUES(14, 'leem@outlook.com', '62986431777', 14);
INSERT INTO CONTATO VALUES(15, 'collinsdo@globo.com', '67993785071', 15);
INSERT INTO CONTATO VALUES(16, 'jgeorge21@live.com', '88975778392', 16);
INSERT INTO CONTATO VALUES(17, 'boydrenea@gov.br', '86998819333', 17);
INSERT INTO CONTATO VALUES(18, 'braycrazy@globo.com', '96981763166', 18);
INSERT INTO CONTATO VALUES(19, 'sonny@hotmail.com', '99972777271', 19);
INSERT INTO CONTATO VALUES(20, 'margy_dg@outlook.com', '69986987760', 20);
INSERT INTO CONTATO VALUES(21, NULL, '21983188564', 1);
INSERT INTO CONTATO VALUES(22, NULL, '42981028030', 2);
INSERT INTO CONTATO VALUES(23, NULL, '96975936327', 3);
INSERT INTO CONTATO VALUES(24, NULL, '96976832362', 4);
INSERT INTO CONTATO VALUES(25, NULL, '62988381292', 5);

# INSERINDO AMIGO
INSERT INTO AMIGO VALUES(1, 'Kira Clements');
INSERT INTO AMIGO VALUES(2, 'Londa Rodrigues');
INSERT INTO AMIGO VALUES(3, 'Louie Tyler');
INSERT INTO AMIGO VALUES(4, 'Louie Tyler');
INSERT INTO AMIGO VALUES(5, 'Maricruz Richmond');
INSERT INTO AMIGO VALUES(6, 'Deadra Rice');
INSERT INTO AMIGO VALUES(7, 'Teena Sanderson');
INSERT INTO AMIGO VALUES(8, 'Herman Allen');
INSERT INTO AMIGO VALUES(9, 'Vania Conway');
INSERT INTO AMIGO VALUES(10, 'Booker Sheridan');
INSERT INTO AMIGO VALUES(11, 'Kathey Emery');
INSERT INTO AMIGO VALUES(12, 'Shenita White');
INSERT INTO AMIGO VALUES(13, 'Linette Williamson');
INSERT INTO AMIGO VALUES(14, 'Jacques Booth');
INSERT INTO AMIGO VALUES(15, 'Vergie Bowers');
INSERT INTO AMIGO VALUES(16, 'Clare Delamarre');
INSERT INTO AMIGO VALUES(17, 'Laurel Spencer');
INSERT INTO AMIGO VALUES(18, 'Thurman Gilmour');
INSERT INTO AMIGO VALUES(19, 'Consuela Rowe');
INSERT INTO AMIGO VALUES(20, 'Shela Bell');
INSERT INTO AMIGO VALUES(21, 'Merri Lambert');
INSERT INTO AMIGO VALUES(22, 'Tisha Millington');
INSERT INTO AMIGO VALUES(23, 'Angelo Hawkins');
INSERT INTO AMIGO VALUES(24, 'Whitley Browning');
INSERT INTO AMIGO VALUES(25, 'Lourdes Cox');
INSERT INTO AMIGO VALUES(26, 'Luvenia Franks');
INSERT INTO AMIGO VALUES(27, 'Letisha Joseph');
INSERT INTO AMIGO VALUES(28, 'Joel Mckenzie');
INSERT INTO AMIGO VALUES(29, 'Devorah Barron');
INSERT INTO AMIGO VALUES(30, 'Bobby Gonzalez');

# INSERINDO AMIGO DO USUARIO
INSERT INTO USUARIO_AMIGO VALUES(16, 1);
INSERT INTO USUARIO_AMIGO VALUES(11, 2);
INSERT INTO USUARIO_AMIGO VALUES(1, 3);
INSERT INTO USUARIO_AMIGO VALUES(17, 4);
INSERT INTO USUARIO_AMIGO VALUES(3, 5);
INSERT INTO USUARIO_AMIGO VALUES(17, 6);
INSERT INTO USUARIO_AMIGO VALUES(2, 7);
INSERT INTO USUARIO_AMIGO VALUES(4, 8);
INSERT INTO USUARIO_AMIGO VALUES(11, 9);
INSERT INTO USUARIO_AMIGO VALUES(20, 10);
INSERT INTO USUARIO_AMIGO VALUES(19, 11);
INSERT INTO USUARIO_AMIGO VALUES(6, 12);
INSERT INTO USUARIO_AMIGO VALUES(20, 13);
INSERT INTO USUARIO_AMIGO VALUES(3, 14);
INSERT INTO USUARIO_AMIGO VALUES(20, 15);
INSERT INTO USUARIO_AMIGO VALUES(11, 16);
INSERT INTO USUARIO_AMIGO VALUES(4, 17);
INSERT INTO USUARIO_AMIGO VALUES(10, 18);
INSERT INTO USUARIO_AMIGO VALUES(15, 19);
INSERT INTO USUARIO_AMIGO VALUES(20, 20);
INSERT INTO USUARIO_AMIGO VALUES(5, 21);
INSERT INTO USUARIO_AMIGO VALUES(10, 22);
INSERT INTO USUARIO_AMIGO VALUES(15, 23);
INSERT INTO USUARIO_AMIGO VALUES(5, 24);
INSERT INTO USUARIO_AMIGO VALUES(15, 25);
INSERT INTO USUARIO_AMIGO VALUES(12, 26);
INSERT INTO USUARIO_AMIGO VALUES(20, 27);
INSERT INTO USUARIO_AMIGO VALUES(16, 28);
INSERT INTO USUARIO_AMIGO VALUES(7, 29);
INSERT INTO USUARIO_AMIGO VALUES(13, 30);

# INSERINDO DATA E HORA DA PUBLICAÇÃO
INSERT INTO DATAHORA_PUBLI VALUES(1, '26/06/2022', '10:24');
INSERT INTO DATAHORA_PUBLI VALUES(2, '28/06/2022', '12:30');
INSERT INTO DATAHORA_PUBLI VALUES(3, '29/06/2022', '22:02');
INSERT INTO DATAHORA_PUBLI VALUES(4, '29/06/2022', '23:12');
INSERT INTO DATAHORA_PUBLI VALUES(5, '04/04/2022', '14:14');
INSERT INTO DATAHORA_PUBLI VALUES(6, '01/04/2022', '00:32');
INSERT INTO DATAHORA_PUBLI VALUES(7, '21/03/2022', '03:45');
INSERT INTO DATAHORA_PUBLI VALUES(8, '25/05/2022', '05:22');

# INSERINDO PUBLICACAO
INSERT INTO PUBLICACAO VALUES(1, 'TEXTO', 'GOOOOLLLLLLL DO FLAMENGO', NULL, NULL, NULL, NULL, 3, NULL, NULL);
INSERT INTO PUBLICACAO VALUES(2, 'TEXTO', 'GOOOOLLLLLLL DO VASCO', NULL, NULL, NULL, NULL, 4, NULL, NULL);
INSERT INTO PUBLICACAO VALUES(3, 'TEXTO', 'JÁ CONHECERAM A NOVA FUNÇÃO DO PYTHON?', NULL, NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO PUBLICACAO VALUES(4, 'VIDEO', NULL, 'SAADA4S9SAX.MP4', '2:30', NULL, NULL, 5, NULL, NULL);
INSERT INTO PUBLICACAO VALUES(5, 'VIDEO', NULL, 'XEROX.MP4', '5:32', NULL, NULL, 2, NULL, NULL);
INSERT INTO PUBLICACAO VALUES(6, 'VIDEO', NULL, 'FLORES.MP4', '1:10', NULL, NULL, 6, NULL, NULL);
INSERT INTO PUBLICACAO VALUES(7, 'VIDEO', NULL, 'GOLVASCO.MP4', '2:35', NULL, NULL, 7, NULL, NULL);
INSERT INTO PUBLICACAO VALUES(8, 'FOTO', NULL, NULL, NULL, 'FLORES,JPEG', '21kb', 8, NULL, NULL);


# INSERINDO CURTIDA
INSERT INTO CURTIDA VALUES('Kira Clements', 1);
INSERT INTO CURTIDA VALUES('Bobby Gonzalez', 2);
INSERT INTO CURTIDA VALUES('Devorah Barron', 1);
INSERT INTO CURTIDA VALUES('Devorah Barron', 3);
INSERT INTO CURTIDA VALUES('Merri Lambert', 1);
INSERT INTO CURTIDA VALUES('Devorah Barron', 4);
INSERT INTO CURTIDA VALUES('Merri Lambert', 5);
INSERT INTO CURTIDA VALUES('Angelo Hawkins', 6);
INSERT INTO CURTIDA VALUES('Angelo Hawkins', 2);
INSERT INTO CURTIDA VALUES('Vania Conway', 3);
INSERT INTO CURTIDA VALUES('Clare Delamarre', 2);
INSERT INTO CURTIDA VALUES('Linette Williamson', 2);
INSERT INTO CURTIDA VALUES('Shela Bell', 2);
INSERT INTO CURTIDA VALUES('Shela Bell', 1);
INSERT INTO CURTIDA VALUES('Clare Delamarre', 1);
INSERT INTO CURTIDA VALUES('Vergie Bowers', 1);
INSERT INTO CURTIDA VALUES('Consuela Rowe', 3);
INSERT INTO CURTIDA VALUES('Vergie Bowers', 3);
INSERT INTO CURTIDA VALUES('Linette Williamson', 3);
INSERT INTO CURTIDA VALUES('Jacques Booth', 7);
INSERT INTO CURTIDA VALUES('Consuela Rowe', 7);
INSERT INTO CURTIDA VALUES('Thurman Gilmour', 7);
INSERT INTO CURTIDA VALUES('Jacques Booth', 5);

# INSERINDO COMPARTILHAMENTO
INSERT INTO COMPARTILHAMENTO VALUES('Kira Clements', 1);
INSERT INTO COMPARTILHAMENTO VALUES('Bobby Gonzalez', 2);
INSERT INTO COMPARTILHAMENTO VALUES('Devorah Barron', 1);
INSERT INTO COMPARTILHAMENTO VALUES('Devorah Barron', 3);
INSERT INTO COMPARTILHAMENTO VALUES('Merri Lambert', 1);
INSERT INTO COMPARTILHAMENTO VALUES('Devorah Barron', 4);
INSERT INTO COMPARTILHAMENTO VALUES('Merri Lambert', 5);
INSERT INTO COMPARTILHAMENTO VALUES('Angelo Hawkins', 6);
INSERT INTO COMPARTILHAMENTO VALUES('Angelo Hawkins', 2);
INSERT INTO COMPARTILHAMENTO VALUES('Vania Conway', 3);
INSERT INTO COMPARTILHAMENTO VALUES('Clare Delamarre', 2);
INSERT INTO COMPARTILHAMENTO VALUES('Linette Williamson', 2);
INSERT INTO COMPARTILHAMENTO VALUES('Shela Bell', 2);
INSERT INTO COMPARTILHAMENTO VALUES('Shela Bell', 1);
INSERT INTO COMPARTILHAMENTO VALUES('Clare Delamarre', 1);
INSERT INTO COMPARTILHAMENTO VALUES('Vergie Bowers', 1);
INSERT INTO COMPARTILHAMENTO VALUES('Consuela Rowe', 3);
INSERT INTO COMPARTILHAMENTO VALUES('Vergie Bowers', 3);
INSERT INTO COMPARTILHAMENTO VALUES('Linette Williamson', 3);
INSERT INTO COMPARTILHAMENTO VALUES('Jacques Booth', 7);
INSERT INTO COMPARTILHAMENTO VALUES('Consuela Rowe', 7);
INSERT INTO COMPARTILHAMENTO VALUES('Thurman Gilmour', 7);
INSERT INTO COMPARTILHAMENTO VALUES('Jacques Booth', 5);

# INSERINDO USUARIO NOS GRUPOS

INSERT INTO USUARIO_GRUPO VALUES(3, 6);
INSERT INTO USUARIO_GRUPO VALUES(4, 1);
INSERT INTO USUARIO_GRUPO VALUES(17, 5);
INSERT INTO USUARIO_GRUPO VALUES(20, 1);
INSERT INTO USUARIO_GRUPO VALUES(9, 2);
INSERT INTO USUARIO_GRUPO VALUES(17, 6);
INSERT INTO USUARIO_GRUPO VALUES(2, 5);
INSERT INTO USUARIO_GRUPO VALUES(18, 3);
INSERT INTO USUARIO_GRUPO VALUES(9, 5);
INSERT INTO USUARIO_GRUPO VALUES(20, 5);
INSERT INTO USUARIO_GRUPO VALUES(15, 5);
INSERT INTO USUARIO_GRUPO VALUES(20, 6);
INSERT INTO USUARIO_GRUPO VALUES(13, 4);
INSERT INTO USUARIO_GRUPO VALUES(16, 6);
INSERT INTO USUARIO_GRUPO VALUES(19, 3);
INSERT INTO USUARIO_GRUPO VALUES(8, 6);
INSERT INTO USUARIO_GRUPO VALUES(13, 6);

# INSERINDO O DONO DA PUBLICACAO
INSERT INTO USUARIO_PUBLICACAO VALUES(20, 6);
INSERT INTO USUARIO_PUBLICACAO VALUES(11, 5);
INSERT INTO USUARIO_PUBLICACAO VALUES(15, 2);
INSERT INTO USUARIO_PUBLICACAO VALUES(9, 1);
INSERT INTO USUARIO_PUBLICACAO VALUES(17, 4);
INSERT INTO USUARIO_PUBLICACAO VALUES(1, 8);
INSERT INTO USUARIO_PUBLICACAO VALUES(19, 7);
INSERT INTO USUARIO_PUBLICACAO VALUES(7, 3);

# INSERINDO SEGUIDOR
INSERT INTO SEGUIDOR VALUES(1, 'Alfie Allen');
INSERT INTO SEGUIDOR VALUES(2, 'Bryce Dallas Howard');
INSERT INTO SEGUIDOR VALUES(3, 'Cobie Smulders');
INSERT INTO SEGUIDOR VALUES(4, 'Zooey Deschanel');
INSERT INTO SEGUIDOR VALUES(5, 'Christina Ricci');
INSERT INTO SEGUIDOR VALUES(6, 'Elisha Cuthbert');
INSERT INTO SEGUIDOR VALUES(7, 'Dwayne Johnson');
INSERT INTO SEGUIDOR VALUES(8, 'Renée Zellweger');
INSERT INTO SEGUIDOR VALUES(9, 'Tom Hardy');
INSERT INTO SEGUIDOR VALUES(10, 'Michael Fassbender');
INSERT INTO SEGUIDOR VALUES(11, 'Sarah Shahi');
INSERT INTO SEGUIDOR VALUES(12, 'Heath Ledger');
INSERT INTO SEGUIDOR VALUES(13, 'Margot Robbie');
INSERT INTO SEGUIDOR VALUES(14, 'Diane Lane');
INSERT INTO SEGUIDOR VALUES(15, 'Lindsey Shaw');
INSERT INTO SEGUIDOR VALUES(16, 'Matt Bomer');
INSERT INTO SEGUIDOR VALUES(17, 'Sofia Coppola');
INSERT INTO SEGUIDOR VALUES(18, 'Kate Hudson');
INSERT INTO SEGUIDOR VALUES(19, 'Edward Norton');
INSERT INTO SEGUIDOR VALUES(20, 'Roberto Orci');
INSERT INTO SEGUIDOR VALUES(21, 'Evan Rachel Wood');
INSERT INTO SEGUIDOR VALUES(22, 'Sofía Vergara');

# INSERINDO SEGUIDOR AO USUARIO
INSERT INTO USUARIO_SEGUIDOR VALUES(17, 18);
INSERT INTO USUARIO_SEGUIDOR VALUES(7, 14);
INSERT INTO USUARIO_SEGUIDOR VALUES(6, 9);
INSERT INTO USUARIO_SEGUIDOR VALUES(7, 22);
INSERT INTO USUARIO_SEGUIDOR VALUES(19, 22);
INSERT INTO USUARIO_SEGUIDOR VALUES(3, 8);
INSERT INTO USUARIO_SEGUIDOR VALUES(7, 20);
INSERT INTO USUARIO_SEGUIDOR VALUES(11, 5);
INSERT INTO USUARIO_SEGUIDOR VALUES(11, 20);
INSERT INTO USUARIO_SEGUIDOR VALUES(6, 18);
INSERT INTO USUARIO_SEGUIDOR VALUES(15, 16);
INSERT INTO USUARIO_SEGUIDOR VALUES(19, 17);
INSERT INTO USUARIO_SEGUIDOR VALUES(6, 13);
INSERT INTO USUARIO_SEGUIDOR VALUES(7, 15);
INSERT INTO USUARIO_SEGUIDOR VALUES(15, 11);
INSERT INTO USUARIO_SEGUIDOR VALUES(1, 3);
INSERT INTO USUARIO_SEGUIDOR VALUES(15, 14);
INSERT INTO USUARIO_SEGUIDOR VALUES(4, 12);
INSERT INTO USUARIO_SEGUIDOR VALUES(8, 8);
INSERT INTO USUARIO_SEGUIDOR VALUES(16, 17);
INSERT INTO USUARIO_SEGUIDOR VALUES(12, 10);
INSERT INTO USUARIO_SEGUIDOR VALUES(13, 11);
INSERT INTO USUARIO_SEGUIDOR VALUES(13, 9);
INSERT INTO USUARIO_SEGUIDOR VALUES(8, 20);
INSERT INTO USUARIO_SEGUIDOR VALUES(2, 9);
INSERT INTO USUARIO_SEGUIDOR VALUES(19, 4);
INSERT INTO USUARIO_SEGUIDOR VALUES(17, 7);
INSERT INTO USUARIO_SEGUIDOR VALUES(12, 10);
